// frontend/src/pages/Favorites.tsx
import { useState, useMemo } from 'react'
import { Card, Skeleton } from '@/components/ui'
import { useFavorites } from '@/hooks/useStats'
import { useServer } from '@/contexts/ServerContext'
import { Heart, Users, Film, Tv, ChevronDown, ChevronUp, Search, User } from 'lucide-react'
import type { FavoriteItem, UserFavorites, UserFavoriteItem } from '@/types'

type ViewMode = 'users' | 'ranking'
type FilterType = 'all' | 'Movie' | 'Series'

export function Favorites() {
  const { currentServer } = useServer()
  // 将 server_id 作为参数传入，确保服务器切换时数据会刷新
  const { data, loading } = useFavorites({ server_id: currentServer?.id || '' })
  const [viewMode, setViewMode] = useState<ViewMode>('users')
  const [expandedUsers, setExpandedUsers] = useState<Set<string>>(new Set())
  const [expandedItems, setExpandedItems] = useState<Set<string>>(new Set())
  const [filter, setFilter] = useState<FilterType>('all')
  const [searchQuery, setSearchQuery] = useState('')

  const items = data?.items ?? []
  const usersFavorites = data?.users_favorites ?? []
  const totalUsers = data?.total_users ?? 0
  const usersWithFavorites = data?.users_with_favorites ?? 0

  // 搜索和筛选逻辑
  const filteredUsersFavorites = useMemo(() => {
    return usersFavorites
      .map(user => {
        let filtered = user.favorites
        // 类型筛选
        if (filter !== 'all') {
          filtered = filtered.filter(item => item.type === filter)
        }
        // 搜索筛选
        if (searchQuery.trim()) {
          const query = searchQuery.toLowerCase()
          filtered = filtered.filter(item =>
            item.name.toLowerCase().includes(query) ||
            (item.series_name && item.series_name.toLowerCase().includes(query))
          )
        }
        return { ...user, favorites: filtered, favorite_count: filtered.length }
      })
      .filter(user => {
        // 如果有搜索词，只显示有匹配结果的用户
        if (searchQuery.trim()) {
          return user.favorites.length > 0
        }
        // 如果搜索用户名
        if (searchQuery.trim() && user.username.toLowerCase().includes(searchQuery.toLowerCase())) {
          return true
        }
        return user.favorites.length > 0
      })
  }, [usersFavorites, filter, searchQuery])

  const filteredItems = useMemo(() => {
    let filtered = items
    // 类型筛选
    if (filter !== 'all') {
      filtered = filtered.filter(item => item.type === filter)
    }
    // 搜索筛选
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase()
      filtered = filtered.filter(item =>
        item.name.toLowerCase().includes(query) ||
        (item.series_name && item.series_name.toLowerCase().includes(query)) ||
        item.users.some(u => u.username.toLowerCase().includes(query))
      )
    }
    return filtered
  }, [items, filter, searchQuery])

  const toggleUserExpand = (userId: string) => {
    setExpandedUsers(prev => {
      const next = new Set(prev)
      if (next.has(userId)) {
        next.delete(userId)
      } else {
        next.add(userId)
      }
      return next
    })
  }

  const toggleItemExpand = (itemId: string) => {
    setExpandedItems(prev => {
      const next = new Set(prev)
      if (next.has(itemId)) {
        next.delete(itemId)
      } else {
        next.add(itemId)
      }
      return next
    })
  }

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'Movie':
        return <Film className="w-4 h-4" />
      case 'Series':
        return <Tv className="w-4 h-4" />
      default:
        return <Heart className="w-4 h-4" />
    }
  }

  const getTypeLabel = (type: string) => {
    switch (type) {
      case 'Movie':
        return '电影'
      case 'Series':
        return '剧集'
      default:
        return type
    }
  }

  return (
    <div className="space-y-4">
      {/* 统计概览 */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        <Card className="p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-pink-500/10">
              <Heart className="w-5 h-5 text-pink-500" />
            </div>
            <div>
              <p className="text-xs text-default-400">收藏内容</p>
              {loading ? (
                <Skeleton className="h-6 w-12 mt-1" />
              ) : (
                <p className="text-xl font-semibold">{items.length}</p>
              )}
            </div>
          </div>
        </Card>
        <Card className="p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-blue-500/10">
              <Users className="w-5 h-5 text-blue-500" />
            </div>
            <div>
              <p className="text-xs text-default-400">有收藏的用户</p>
              {loading ? (
                <Skeleton className="h-6 w-12 mt-1" />
              ) : (
                <p className="text-xl font-semibold">{usersWithFavorites} / {totalUsers}</p>
              )}
            </div>
          </div>
        </Card>
        <Card className="p-4 col-span-2 sm:col-span-1">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-purple-500/10">
              <Film className="w-5 h-5 text-purple-500" />
            </div>
            <div>
              <p className="text-xs text-default-400">电影 / 剧集</p>
              {loading ? (
                <Skeleton className="h-6 w-16 mt-1" />
              ) : (
                <p className="text-xl font-semibold">
                  {items.filter(i => i.type === 'Movie').length} / {items.filter(i => i.type === 'Series').length}
                </p>
              )}
            </div>
          </div>
        </Card>
      </div>

      {/* 主内容区 */}
      <Card className="p-4 sm:p-5" hover={false}>
        {/* 顶部控制栏 */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4 relative z-20">
          {/* 视图切换 Tab */}
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => setViewMode('users')}
              className={`px-4 py-2 text-sm rounded-lg transition-colors flex items-center gap-2 cursor-pointer select-none relative z-10 ${
                viewMode === 'users'
                  ? 'bg-primary text-white'
                  : 'bg-default-100 hover:bg-default-200'
              }`}
            >
              <User className="w-4 h-4" />
              按用户
            </button>
            <button
              type="button"
              onClick={() => setViewMode('ranking')}
              className={`px-4 py-2 text-sm rounded-lg transition-colors flex items-center gap-2 cursor-pointer select-none relative z-10 ${
                viewMode === 'ranking'
                  ? 'bg-primary text-white'
                  : 'bg-default-100 hover:bg-default-200'
              }`}
            >
              <Heart className="w-4 h-4" />
              热门榜单
            </button>
          </div>

          {/* 类型筛选 */}
          <div className="flex gap-2">
            <button
              type="button"
              onClick={() => setFilter('all')}
              className={`px-3 py-1 text-xs rounded-full transition-colors cursor-pointer select-none relative z-10 ${
                filter === 'all'
                  ? 'bg-primary text-white'
                  : 'bg-default-100 hover:bg-default-200'
              }`}
            >
              全部
            </button>
            <button
              type="button"
              onClick={() => setFilter('Movie')}
              className={`px-3 py-1 text-xs rounded-full transition-colors cursor-pointer select-none relative z-10 ${
                filter === 'Movie'
                  ? 'bg-primary text-white'
                  : 'bg-default-100 hover:bg-default-200'
              }`}
            >
              电影
            </button>
            <button
              type="button"
              onClick={() => setFilter('Series')}
              className={`px-3 py-1 text-xs rounded-full transition-colors cursor-pointer select-none relative z-10 ${
                filter === 'Series'
                  ? 'bg-primary text-white'
                  : 'bg-default-100 hover:bg-default-200'
              }`}
            >
              剧集
            </button>
          </div>
        </div>

        {/* 搜索框 */}
        <div className="relative mb-4">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-default-400" />
          <input
            type="text"
            placeholder={viewMode === 'users' ? '搜索用户或内容...' : '搜索内容或用户...'}
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-10 pr-4 py-2 bg-default-100 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
          />
        </div>

        {/* 内容列表 */}
        {loading ? (
          <div className="space-y-3">
            {[...Array(6)].map((_, i) => (
              <Skeleton key={i} className="h-20 w-full rounded-lg" />
            ))}
          </div>
        ) : viewMode === 'users' ? (
          // 按用户视图
          filteredUsersFavorites.length === 0 ? (
            <p className="text-center text-default-400 py-8">
              {searchQuery ? '没有找到匹配的结果' : '暂无收藏数据'}
            </p>
          ) : (
            <div className="space-y-3">
              {filteredUsersFavorites.map((user) => (
                <UserFavoritesCard
                  key={user.user_id}
                  user={user}
                  expanded={expandedUsers.has(user.user_id)}
                  onToggle={() => toggleUserExpand(user.user_id)}
                  getTypeIcon={getTypeIcon}
                  getTypeLabel={getTypeLabel}
                  serverId={currentServer?.id}
                />
              ))}
            </div>
          )
        ) : (
          // 热门榜单视图
          filteredItems.length === 0 ? (
            <p className="text-center text-default-400 py-8">
              {searchQuery ? '没有找到匹配的结果' : '暂无收藏数据'}
            </p>
          ) : (
            <div className="space-y-3">
              {filteredItems.map((item, index) => (
                <FavoriteItemCard
                  key={item.item_id}
                  item={item}
                  rank={index + 1}
                  expanded={expandedItems.has(item.item_id)}
                  onToggle={() => toggleItemExpand(item.item_id)}
                  getTypeIcon={getTypeIcon}
                  getTypeLabel={getTypeLabel}
                  serverId={currentServer?.id}
                />
              ))}
            </div>
          )
        )}
      </Card>
    </div>
  )
}

// 用户收藏卡片组件
interface UserFavoritesCardProps {
  user: UserFavorites
  expanded: boolean
  onToggle: () => void
  getTypeIcon: (type: string) => React.ReactNode
  getTypeLabel: (type: string) => string
  serverId?: string
}

function UserFavoritesCard({ user, expanded, onToggle, getTypeIcon, getTypeLabel, serverId }: UserFavoritesCardProps) {
  const movieCount = user.favorites.filter(f => f.type === 'Movie').length
  const seriesCount = user.favorites.filter(f => f.type === 'Series').length
  // 构建带 server_id 的海报 URL
  const getPosterUrl = (posterId: string, maxHeight: number, maxWidth: number) => {
    const params = new URLSearchParams({ maxHeight: String(maxHeight), maxWidth: String(maxWidth) })
    if (serverId) params.set('server_id', serverId)
    return `/api/poster/${posterId}?${params.toString()}`
  }
  // 显示前 5 个海报
  const previewItems = user.favorites.slice(0, 5)

  return (
    <div className="bg-default-50 rounded-lg overflow-hidden">
      <div
        className="flex items-center gap-3 p-3 cursor-pointer hover:bg-default-100 transition-colors"
        onClick={onToggle}
      >
        {/* 用户头像 */}
        <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-purple-500 flex items-center justify-center flex-shrink-0">
          <span className="text-white font-semibold text-sm">
            {user.username.charAt(0).toUpperCase()}
          </span>
        </div>

        {/* 用户信息 */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <h4 className="font-medium text-sm">{user.username}</h4>
            <span className="text-xs text-default-400">
              收藏 {user.favorite_count} 部
            </span>
          </div>
          <div className="flex items-center gap-3 mt-1 text-xs text-default-400">
            {movieCount > 0 && (
              <span className="flex items-center gap-1">
                <Film className="w-3 h-3" />
                {movieCount} 电影
              </span>
            )}
            {seriesCount > 0 && (
              <span className="flex items-center gap-1">
                <Tv className="w-3 h-3" />
                {seriesCount} 剧集
              </span>
            )}
          </div>
        </div>

        {/* 海报预览 */}
        <div className="hidden sm:flex items-center gap-1">
          {previewItems.map((item) => {
            const posterId = item.series_id || item.item_id
            return (
              <div
                key={item.item_id}
                className="w-8 h-12 rounded overflow-hidden bg-default-200 flex-shrink-0"
              >
                {item.has_poster ? (
                  <img
                    src={getPosterUrl(posterId, 192, 128)}
                    alt={item.name}
                    className="w-full h-full object-cover"
                    loading="lazy"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center">
                    {getTypeIcon(item.type)}
                  </div>
                )}
              </div>
            )
          })}
          {user.favorites.length > 5 && (
            <div className="w-8 h-12 rounded bg-default-200 flex items-center justify-center text-xs text-default-400">
              +{user.favorites.length - 5}
            </div>
          )}
        </div>

        {/* 展开图标 */}
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 text-pink-500">
            <Heart className="w-4 h-4 fill-current" />
            <span className="font-semibold">{user.favorite_count}</span>
          </div>
          {expanded ? (
            <ChevronUp className="w-4 h-4 text-default-400" />
          ) : (
            <ChevronDown className="w-4 h-4 text-default-400" />
          )}
        </div>
      </div>

      {/* 展开的收藏列表 */}
      {expanded && (
        <div className="px-3 pb-3 pt-0">
          <div className="bg-default-100 rounded-lg p-3">
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
              {user.favorites.map((item) => (
                <UserFavoriteItemCard
                  key={item.item_id}
                  item={item}
                  getTypeIcon={getTypeIcon}
                  getTypeLabel={getTypeLabel}
                  serverId={serverId}
                />
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// 用户收藏的单个项目卡片
interface UserFavoriteItemCardProps {
  item: UserFavoriteItem
  getTypeIcon: (type: string) => React.ReactNode
  getTypeLabel: (type: string) => string
  serverId?: string
}

function UserFavoriteItemCard({ item, getTypeIcon, getTypeLabel, serverId }: UserFavoriteItemCardProps) {
  const posterId = item.series_id || item.item_id
  // 构建带 server_id 的海报 URL
  const getPosterUrl = () => {
    const params = new URLSearchParams({ maxHeight: '720', maxWidth: '480' })
    if (serverId) params.set('server_id', serverId)
    return `/api/poster/${posterId}?${params.toString()}`
  }

  return (
    <div className="bg-default-50 rounded-lg overflow-hidden">
      {/* 海报 */}
      <div className="aspect-[2/3] bg-default-200 relative">
        {item.has_poster ? (
          <img
            src={getPosterUrl()}
            alt={item.name}
            className="w-full h-full object-cover"
            loading="lazy"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center">
            {getTypeIcon(item.type)}
          </div>
        )}
        {/* 类型标签 */}
        <div className="absolute top-1 right-1 px-1.5 py-0.5 bg-black/60 rounded text-[10px] text-white">
          {getTypeLabel(item.type)}
        </div>
      </div>
      {/* 信息 */}
      <div className="p-2">
        <p className="text-xs font-medium truncate" title={item.name}>
          {item.name}
        </p>
        {item.year && (
          <p className="text-[10px] text-default-400">{item.year}</p>
        )}
        {item.series_name && (
          <p className="text-[10px] text-default-400 truncate" title={item.series_name}>
            {item.series_name}
          </p>
        )}
      </div>
    </div>
  )
}

// 热门榜单项目卡片（保留原有设计）
interface FavoriteItemCardProps {
  item: FavoriteItem
  rank: number
  expanded: boolean
  onToggle: () => void
  getTypeIcon: (type: string) => React.ReactNode
  getTypeLabel: (type: string) => string
  serverId?: string
}

function FavoriteItemCard({ item, rank, expanded, onToggle, getTypeIcon, getTypeLabel, serverId }: FavoriteItemCardProps) {
  const getRankColor = (rank: number) => {
    switch (rank) {
      case 1:
        return 'text-yellow-500'
      case 2:
        return 'text-gray-400'
      case 3:
        return 'text-amber-600'
      default:
        return 'text-default-400'
    }
  }

  const posterId = item.series_id || item.item_id
  // 构建带 server_id 的海报 URL
  const getPosterUrl = () => {
    const params = new URLSearchParams({ maxHeight: '256', maxWidth: '192' })
    if (serverId) params.set('server_id', serverId)
    return `/api/poster/${posterId}?${params.toString()}`
  }

  return (
    <div className="bg-default-50 rounded-lg overflow-hidden">
      <div
        className="flex items-center gap-3 p-3 cursor-pointer hover:bg-default-100 transition-colors"
        onClick={onToggle}
      >
        {/* 排名 */}
        <div className={`w-8 text-center font-bold ${getRankColor(rank)}`}>
          #{rank}
        </div>

        {/* 海报 */}
        <div className="w-12 h-16 flex-shrink-0 rounded overflow-hidden bg-default-200">
          {item.has_poster ? (
            <img
              src={getPosterUrl()}
              alt={item.name}
              className="w-full h-full object-cover"
              loading="lazy"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center">
              {getTypeIcon(item.type)}
            </div>
          )}
        </div>

        {/* 信息 */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <h4 className="font-medium text-sm truncate">{item.name}</h4>
            {item.year && (
              <span className="text-xs text-default-400">({item.year})</span>
            )}
          </div>
          <div className="flex items-center gap-2 mt-1">
            <span className="inline-flex items-center gap-1 text-xs text-default-400">
              {getTypeIcon(item.type)}
              {getTypeLabel(item.type)}
            </span>
            {item.series_name && (
              <span className="text-xs text-default-400 truncate">
                {item.series_name}
              </span>
            )}
          </div>
        </div>

        {/* 收藏人数 */}
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 text-pink-500">
            <Heart className="w-4 h-4 fill-current" />
            <span className="font-semibold">{item.favorite_count}</span>
          </div>
          {expanded ? (
            <ChevronUp className="w-4 h-4 text-default-400" />
          ) : (
            <ChevronDown className="w-4 h-4 text-default-400" />
          )}
        </div>
      </div>

      {/* 展开的用户列表 */}
      {expanded && (
        <div className="px-3 pb-3 pt-0">
          <div className="bg-default-100 rounded-lg p-3">
            <p className="text-xs text-default-400 mb-2">收藏用户：</p>
            <div className="flex flex-wrap gap-2">
              {item.users.map(user => (
                <span
                  key={user.user_id}
                  className="inline-flex items-center gap-1 px-2 py-1 bg-default-200 rounded-full text-xs"
                >
                  <Users className="w-3 h-3" />
                  {user.username}
                </span>
              ))}
            </div>
            {item.overview && (
              <p className="text-xs text-default-400 mt-3 line-clamp-3">
                {item.overview}
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// frontend-vue/src/pages/Favorites.vue
<template>
  <div class="page">
    <PageHeader title="收藏统计" subtitle="查看用户收藏的内容和热门排行" />

    <v-fade-transition mode="out-in">
      <!-- 加载状态 -->
      <LoadingState v-if="loading" preset="stats-table" />

      <!-- 数据展示 -->
      <div v-else-if="favoritesData">
        <!-- 统计卡片 -->
        <v-row class="mb-6">
        <v-col cols="12" sm="6" md="4">
          <v-card class="pulse-card" hover>
            <v-card-text>
              <div class="stat-content">
                <div class="stat-icon" style="background: rgba(236, 72, 153, 0.1);">
                  <v-icon size="24" color="pink">mdi-heart</v-icon>
                </div>
                <div class="stat-info">
                  <div class="stat-label">收藏内容</div>
                  <AnimatedNumber
                    :value="totalFavoriteItems"
                    class="stat-value"
                    style="color: rgb(236, 72, 153);"
                  />
                </div>
              </div>
            </v-card-text>
          </v-card>
        </v-col>

        <v-col cols="12" sm="6" md="4">
          <v-card class="pulse-card" hover>
            <v-card-text>
              <div class="stat-content">
                <div class="stat-icon" style="background: rgba(59, 130, 246, 0.1);">
                  <v-icon size="24" color="primary">mdi-account-group</v-icon>
                </div>
                <div class="stat-info">
                  <div class="stat-label">有收藏的用户</div>
                  <div class="stat-value text-primary">
                    {{ usersWithFavorites }} / {{ totalUsers }}
                  </div>
                </div>
              </div>
            </v-card-text>
          </v-card>
        </v-col>

        <v-col cols="12" sm="6" md="4">
          <v-card class="pulse-card" hover>
            <v-card-text>
              <div class="stat-content">
                <div class="stat-icon" style="background: rgba(168, 85, 247, 0.1);">
                  <v-icon size="24" color="purple">mdi-filmstrip</v-icon>
                </div>
                <div class="stat-info">
                  <div class="stat-label">电影 / 剧集</div>
                  <div class="stat-value text-purple">
                    {{ movieCount }} / {{ seriesCount }}
                  </div>
                </div>
              </div>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>

      <!-- 主内容区 -->
      <v-card hover>
        <v-card-text>
          <!-- 顶部控制栏 -->
          <div class="d-flex flex-column flex-sm-row justify-space-between align-start mb-4" style="gap: 12px;">
            <!-- 视图切换 -->
            <v-btn-toggle
              v-model="viewMode"
              mandatory
              variant="outlined"
              divided
              density="comfortable"
            >
              <v-btn value="users" prepend-icon="mdi-account">
                按用户
              </v-btn>
              <v-btn value="ranking" prepend-icon="mdi-heart">
                热门榜单
              </v-btn>
            </v-btn-toggle>

            <!-- 类型筛选 -->
            <v-btn-toggle
              v-model="filterType"
              mandatory
              variant="outlined"
              divided
              density="comfortable"
            >
              <v-btn value="all">全部</v-btn>
              <v-btn value="Movie">电影</v-btn>
              <v-btn value="Series">剧集</v-btn>
            </v-btn-toggle>
          </div>

          <!-- 搜索框 -->
          <v-text-field
            v-model="searchQuery"
            :placeholder="viewMode === 'users' ? '搜索用户或内容...' : '搜索内容或用户...'"
            prepend-inner-icon="mdi-magnify"
            variant="outlined"
            density="comfortable"
            hide-details
            clearable
            class="mb-4"
          />

          <!-- 按用户视图 -->
          <template v-if="viewMode === 'users'">
            <div v-if="filteredUsersFavorites.length === 0" class="text-center py-8 text-grey">
              {{ searchQuery ? '没有找到匹配的结果' : '暂无收藏数据' }}
            </div>
            <div v-else class="user-list">
              <v-expansion-panels v-model="expandedUsers" multiple>
                <v-expansion-panel
                  v-for="user in filteredUsersFavorites"
                  :key="user.user_id"
                  :value="user.user_id"
                >
                  <v-expansion-panel-title>
                    <div class="d-flex align-center w-100" style="gap: 12px;">
                      <!-- 用户头像 -->
                      <Avatar :name="user.username" size="40" />

                      <!-- 用户信息 -->
                      <div class="flex-grow-1">
                        <div class="d-flex align-center" style="gap: 8px;">
                          <span class="font-weight-medium">{{ user.username }}</span>
                          <v-chip size="x-small" color="grey">
                            收藏 {{ user.favorite_count }} 部
                          </v-chip>
                        </div>
                        <div class="text-caption text-grey mt-1">
                          <span v-if="user.movie_count > 0">
                            <v-icon size="small">mdi-movie</v-icon> {{ user.movie_count }} 电影
                          </span>
                          <span v-if="user.series_count > 0" class="ml-3">
                            <v-icon size="small">mdi-television</v-icon> {{ user.series_count }} 剧集
                          </span>
                        </div>
                      </div>

                      <!-- 海报预览（桌面端） -->
                      <div class="d-none d-sm-flex align-center" style="gap: 4px;">
                        <div
                          v-for="item in user.preview_items"
                          :key="item.item_id"
                          class="preview-poster"
                        >
                          <v-img
                            v-if="item.poster_url"
                            :src="item.poster_url"
                            aspect-ratio="0.67"
                            cover
                            class="rounded"
                          />
                          <div v-else class="preview-poster-placeholder">
                            <v-icon size="small">mdi-filmstrip</v-icon>
                          </div>
                        </div>
                        <div v-if="user.favorite_count > 5" class="preview-poster-more">
                          +{{ user.favorite_count - 5 }}
                        </div>
                      </div>

                      <!-- 收藏数徽章 -->
                      <div class="d-flex align-center" style="gap: 4px;">
                        <v-icon color="pink">mdi-heart</v-icon>
                        <span class="font-weight-bold text-pink">{{ user.favorite_count }}</span>
                      </div>
                    </div>
                  </v-expansion-panel-title>

                  <v-expansion-panel-text>
                    <v-row class="mt-2">
                      <v-col
                        v-for="item in user.favorites"
                        :key="item.item_id"
                        cols="6"
                        sm="4"
                        md="3"
                        lg="2"
                      >
                        <div class="favorite-item-card" @click="goToDetail(item)">
                          <div class="favorite-item-poster">
                            <v-img
                              v-if="item.poster_url"
                              :src="item.poster_url"
                              aspect-ratio="0.67"
                              cover
                            />
                            <div v-else class="favorite-item-placeholder">
                              <v-icon>mdi-filmstrip</v-icon>
                            </div>
                            <!-- 类型标签 -->
                            <div class="favorite-item-type-badge">
                              {{ item.type === 'Movie' ? '电影' : '剧集' }}
                            </div>
                          </div>
                          <div class="favorite-item-info">
                            <div class="favorite-item-title" :title="item.name">
                              {{ item.name }}
                            </div>
                            <div v-if="item.year" class="favorite-item-year">
                              {{ item.year }}
                            </div>
                          </div>
                        </div>
                      </v-col>
                    </v-row>
                  </v-expansion-panel-text>
                </v-expansion-panel>
              </v-expansion-panels>
            </div>
          </template>

          <!-- 热门榜单视图 -->
          <template v-else>
            <div v-if="filteredItems.length === 0" class="text-center py-8 text-grey">
              {{ searchQuery ? '没有找到匹配的结果' : '暂无收藏数据' }}
            </div>
            <div v-else class="ranking-list">
              <v-expansion-panels v-model="expandedItems" multiple>
                <v-expansion-panel
                  v-for="(item, index) in filteredItems"
                  :key="item.item_id"
                  :value="item.item_id"
                >
                  <v-expansion-panel-title>
                    <div class="d-flex align-center w-100" style="gap: 12px;">
                      <!-- 排名 -->
                      <div class="rank-badge" :class="getRankClass(index + 1)">
                        #{{ index + 1 }}
                      </div>

                      <!-- 海报 -->
                      <div class="ranking-poster">
                        <v-img
                          v-if="item.poster_url"
                          :src="item.poster_url"
                          aspect-ratio="0.67"
                          cover
                          class="rounded"
                        />
                        <div v-else class="ranking-poster-placeholder">
                          <v-icon>mdi-filmstrip</v-icon>
                        </div>
                      </div>

                      <!-- 内容信息 -->
                      <div class="flex-grow-1">
                        <div class="font-weight-medium">{{ item.name }}</div>
                        <div class="text-caption text-grey mt-1">
                          <v-chip size="x-small" :color="item.type === 'Movie' ? 'blue' : 'purple'">
                            {{ item.type === 'Movie' ? '电影' : '剧集' }}
                          </v-chip>
                          <span class="ml-2">{{ item.favorite_count }} 人收藏</span>
                        </div>
                      </div>

                      <!-- 收藏数徽章 -->
                      <div class="d-flex align-center" style="gap: 4px;">
                        <v-icon color="pink">mdi-heart</v-icon>
                        <span class="font-weight-bold text-pink">{{ item.favorite_count }}</span>
                      </div>
                    </div>
                  </v-expansion-panel-title>

                  <v-expansion-panel-text>
                    <div class="mt-2">
                      <div class="text-subtitle-2 mb-2">收藏用户</div>
                      <v-chip-group column>
                        <v-chip
                          v-for="user in item.users"
                          :key="user.user_id"
                          size="small"
                        >
                          <Avatar :name="user.username" size="24" class="mr-2" />
                          {{ user.username }}
                        </v-chip>
                      </v-chip-group>
                    </div>
                  </v-expansion-panel-text>
                </v-expansion-panel>
              </v-expansion-panels>
            </div>
          </template>
        </v-card-text>
      </v-card>
    </div>

      <!-- 空状态 -->
      <EmptyState v-else message="暂无收藏数据" />
    </v-fade-transition>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Avatar, AnimatedNumber, PageHeader, LoadingState, EmptyState } from '@/components/ui'
import { useServerStore, useFilterStore } from '@/stores'
import { useDataFetch } from '@/composables/useDataFetch'
import { usePosterUrl } from '@/composables'
import { statsApi } from '@/services'
import type { UserFavoriteItem, UserFavorites, FavoriteItem, FavoritesData } from '@/types'

const router = useRouter()
const serverStore = useServerStore()
const filterStore = useFilterStore()
const { buildPosterUrl } = usePosterUrl()

const viewMode = ref<'users' | 'ranking'>('users')
const filterType = ref<'all' | 'Movie' | 'Series'>('all')
const searchQuery = ref('')
const expandedUsers = ref<string[]>([])
const expandedItems = ref<string[]>([])

// 扩展类型：添加处理后的海报 URL
interface ProcessedFavoriteItem extends UserFavoriteItem {
  poster_url?: string
}

interface ProcessedUserFavorite {
  user_id: string
  username: string
  favorite_count: number
  favorites: ProcessedFavoriteItem[]
  movie_count: number
  series_count: number
  preview_items: ProcessedFavoriteItem[]
}

interface ProcessedRankingItem extends FavoriteItem {
  poster_url?: string
}

interface ProcessedFavoritesData {
  users_favorites: ProcessedUserFavorite[]
  items: ProcessedRankingItem[]
  total_users: number
  users_with_favorites: number
}

const favoritesData = ref<ProcessedFavoritesData | null>(null)

// 统计数据
const totalFavoriteItems = computed(() => favoritesData.value?.items.length || 0)
const totalUsers = computed(() => favoritesData.value?.total_users || 0)
const usersWithFavorites = computed(() => favoritesData.value?.users_with_favorites || 0)
const movieCount = computed(() => favoritesData.value?.items.filter(i => i.type === 'Movie').length || 0)
const seriesCount = computed(() => favoritesData.value?.items.filter(i => i.type === 'Series').length || 0)

// 筛选后的用户收藏列表
const filteredUsersFavorites = computed(() => {
  if (!favoritesData.value) return []

  return favoritesData.value.users_favorites
    .map(user => {
      let filtered = user.favorites

      // 类型筛选
      if (filterType.value !== 'all') {
        filtered = filtered.filter(item => item.type === filterType.value)
      }

      // 搜索筛选
      if (searchQuery.value.trim()) {
        const query = searchQuery.value.toLowerCase()
        filtered = filtered.filter(item =>
          item.name.toLowerCase().includes(query) ||
          (item.series_name && item.series_name.toLowerCase().includes(query))
        )
      }

      const movieCount = filtered.filter(f => f.type === 'Movie').length
      const seriesCount = filtered.filter(f => f.type === 'Series').length
      const previewItems = filtered.slice(0, 5)

      return {
        ...user,
        favorites: filtered,
        favorite_count: filtered.length,
        movie_count: movieCount,
        series_count: seriesCount,
        preview_items: previewItems
      }
    })
    .filter(user => {
      // 搜索用户名
      if (searchQuery.value.trim() && user.username.toLowerCase().includes(searchQuery.value.toLowerCase())) {
        return true
      }
      return user.favorites.length > 0
    })
})

// 筛选后的排行榜列表
const filteredItems = computed(() => {
  if (!favoritesData.value) return []

  let filtered = favoritesData.value.items

  // 类型筛选
  if (filterType.value !== 'all') {
    filtered = filtered.filter(item => item.type === filterType.value)
  }

  // 搜索筛选
  if (searchQuery.value.trim()) {
    const query = searchQuery.value.toLowerCase()
    filtered = filtered.filter(item =>
      item.name.toLowerCase().includes(query) ||
      item.users.some(u => u.username.toLowerCase().includes(query))
    )
  }

  return filtered
})

// 获取排名样式
function getRankClass(rank: number) {
  switch (rank) {
    case 1: return 'rank-gold'
    case 2: return 'rank-silver'
    case 3: return 'rank-bronze'
    default: return ''
  }
}

// 跳转到详情页
function goToDetail(item: ProcessedFavoriteItem) {
  // 对于剧集，使用 series_id；对于其他类型，使用 item_id
  if (item.type === 'Series') {
    router.push({
      path: `/content/${item.series_id || item.item_id}`
    })
  } else {
    router.push({
      path: `/content/${item.item_id}`
    })
  }
}

// 使用 useDataFetch 处理数据获取
const { loading } = useDataFetch(
  async () => {
    const params = {
      server_id: serverStore.currentServer!.id,
      ...filterStore.buildQueryParams,
    }

    const response = await statsApi.getFavorites(params)
    const data = response.data as FavoritesData

    // 处理用户收藏数据 - 使用 buildPosterUrl 并计算统计
    const usersFavorites: ProcessedUserFavorite[] = (data.users_favorites || []).map((uf: UserFavorites) => {
      const processedFavorites: ProcessedFavoriteItem[] = (uf.favorites || []).map((f: UserFavoriteItem) => ({
        ...f,
        poster_url: f.has_poster ? buildPosterUrl(f.series_id || f.item_id, 'large') : undefined,
      }))

      return {
        user_id: uf.user_id,
        username: uf.username,
        favorite_count: uf.favorite_count,
        favorites: processedFavorites,
        movie_count: processedFavorites.filter(f => f.type === 'Movie').length,
        series_count: processedFavorites.filter(f => f.type === 'Series').length,
        preview_items: processedFavorites.slice(0, 5),
      }
    })

    // 处理排行榜数据 - 使用 buildPosterUrl
    const items: ProcessedRankingItem[] = (data.items || []).map((item: FavoriteItem) => ({
      ...item,
      poster_url: item.has_poster ? buildPosterUrl(item.series_id || item.item_id, 'medium') : undefined,
    }))

    favoritesData.value = {
      users_favorites: usersFavorites,
      items,
      total_users: data.total_users || 0,
      users_with_favorites: data.users_with_favorites || 0
    }
  },
  {
    immediate: true,
    watchFilter: true,
  }
)
</script>

<style scoped>
/* 海报预览样式 */
.preview-poster {
  width: 32px;
  height: 48px;
  border-radius: 4px;
  overflow: hidden;
  background-color: rgb(39, 39, 42);
}

.preview-poster-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgb(39, 39, 42);
}

.preview-poster-more {
  width: 32px;
  height: 48px;
  border-radius: 4px;
  background-color: rgb(39, 39, 42);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  opacity: 0.7;
}

/* 收藏项目卡片 */
.favorite-item-card {
  cursor: pointer;
  transition: transform 0.2s;
  border-radius: 12px;
  overflow: hidden;
}

.favorite-item-card:hover {
  transform: scale(1.03);
}

.favorite-item-poster {
  position: relative;
  background-color: rgb(39, 39, 42);
  border-radius: 8px;
  overflow: hidden;
}

.favorite-item-placeholder {
  aspect-ratio: 0.67;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgb(39, 39, 42);
}

.favorite-item-type-badge {
  position: absolute;
  top: 4px;
  right: 4px;
  padding: 2px 6px;
  background-color: rgba(0, 0, 0, 0.6);
  border-radius: 4px;
  font-size: 10px;
  color: white;
  backdrop-filter: blur(4px);
}

.favorite-item-info {
  padding: 8px 0;
}

.favorite-item-title {
  font-size: 12px;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.favorite-item-year {
  font-size: 10px;
  opacity: 0.6;
  margin-top: 2px;
}

/* 排行榜样式 */
.ranking-poster {
  width: 48px;
  height: 64px;
  border-radius: 4px;
  overflow: hidden;
  background-color: rgb(39, 39, 42);
  flex-shrink: 0;
}

.ranking-poster-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

@media (max-width: 768px) {
  .page {
    padding: 16px;
  }
}
</style>
