// frontend-vue/src/components/charts/HeatmapChart.vue
<template>
  <div class="heatmap-chart">
    <v-chart
      :option="chartOption"
      :autoresize="true"
      :style="{ height: height, width: '100%' }"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { HeatmapChart } from 'echarts/charts'
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
  VisualMapComponent,
} from 'echarts/components'
import type { EChartsOption } from 'echarts'
import type { HourlyItem } from '@/types'

// 注册 ECharts 组件
use([
  CanvasRenderer,
  HeatmapChart,
  TitleComponent,
  TooltipComponent,
  GridComponent,
  VisualMapComponent,
])

interface Props {
  data?: HourlyItem[]
  height?: string
}

const props = withDefaults(defineProps<Props>(), {
  data: () => [],
  height: '400px',
})

const days = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
const hours = Array.from({ length: 24 }, (_, i) => `${i}:00`)

const chartOption = computed<EChartsOption>(() => {
  // 将数据转换为 ECharts 需要的格式 [hour, day, value]
  const heatmapData = props.data.map((item) => [item.hour, item.day, item.count])

  // 计算最大值用于视觉映射
  const maxValue = Math.max(...props.data.map((item) => item.count), 1)

  return {
    tooltip: {
      position: 'top',
      formatter: (params: any) => {
        const hour = hours[params.data[0]]
        const day = days[params.data[1]]
        const count = params.data[2]
        return `${day} ${hour}<br/>播放次数: ${count}`
      },
    },
    grid: {
      left: '10%',
      right: '5%',
      top: '5%',
      bottom: '10%',
      containLabel: true,
    },
    xAxis: {
      type: 'category',
      data: hours,
      splitArea: {
        show: true,
      },
      axisLabel: {
        color: '#ccc',
        interval: 2, // 每隔2小时显示一个标签
      },
      axisLine: {
        lineStyle: {
          color: '#444',
        },
      },
    },
    yAxis: {
      type: 'category',
      data: days,
      splitArea: {
        show: true,
      },
      axisLabel: {
        color: '#ccc',
      },
      axisLine: {
        lineStyle: {
          color: '#444',
        },
      },
    },
    visualMap: {
      min: 0,
      max: maxValue,
      calculable: true,
      orient: 'horizontal',
      left: 'center',
      bottom: '0',
      textStyle: {
        color: '#ccc',
      },
      inRange: {
        color: ['#1a237e', '#1976d2', '#42a5f5', '#81d4fa'],
      },
    },
    series: [
      {
        name: '播放次数',
        type: 'heatmap',
        data: heatmapData,
        label: {
          show: false,
        },
        emphasis: {
          itemStyle: {
            shadowBlur: 10,
            shadowColor: 'rgba(0, 0, 0, 0.5)',
          },
        },
      },
    ],
  }
})
</script>

<style scoped>
.heatmap-chart {
  width: 100%;
}
</style>

// frontend/src/components/charts/HeatmapChart.tsx
import ReactECharts from 'echarts-for-react'
import type { HourlyItem } from '@/types'
import { useTheme } from '@/contexts/ThemeContext'

interface HeatmapChartProps {
  data: HourlyItem[]
}

export function HeatmapChart({ data }: HeatmapChartProps) {
  const { theme } = useTheme()
  const isDark = theme === 'dark'

  const colors = {
    tooltip: {
      bg: isDark ? '#18181b' : '#ffffff',
      border: isDark ? '#27272a' : '#e4e4e7',
      text: isDark ? '#ECEDEE' : '#18181b',
    },
    axis: {
      line: isDark ? '#27272a' : '#e4e4e7',
      label: isDark ? '#71717a' : '#71717a',
    },
    heatmap: {
      min: isDark ? '#18181b' : '#e6f1fe',
      border: isDark ? '#000' : '#fff',
    },
  }

  const days = ['日', '一', '二', '三', '四', '五', '六']
  const hours = Array.from({ length: 24 }, (_, i) => `${i}`)
  const heatmapData = data.map((d) => [d.hour, d.day, d.count])
  const maxCount = Math.max(...data.map((d) => d.count), 1)

  const option = {
    backgroundColor: 'transparent',
    tooltip: {
      backgroundColor: colors.tooltip.bg,
      borderColor: colors.tooltip.border,
      textStyle: { color: colors.tooltip.text, fontSize: 12 },
      formatter: (p: { data: number[] }) =>
        `周${days[p.data[1]]} ${p.data[0]}:00<br/>播放 ${p.data[2]} 次`,
    },
    grid: { left: '14%', right: '6%', top: '5%', bottom: '12%' },
    xAxis: {
      type: 'category',
      data: hours,
      axisLine: { lineStyle: { color: colors.axis.line } },
      axisLabel: { color: colors.axis.label, fontSize: 10, interval: 3 },
      axisTick: { show: false },
    },
    yAxis: {
      type: 'category',
      data: days,
      axisLine: { lineStyle: { color: colors.axis.line } },
      axisLabel: { color: colors.axis.label, fontSize: 10 },
      axisTick: { show: false },
    },
    visualMap: {
      min: 0,
      max: maxCount,
      show: false,
      inRange: { color: [colors.heatmap.min, '#004493', '#006FEE', '#338ef7'] },
    },
    series: [
      {
        type: 'heatmap',
        data: heatmapData,
        label: { show: false },
        itemStyle: { borderRadius: 3, borderColor: colors.heatmap.border, borderWidth: 1 },
      },
    ],
  }

  return (
    <ReactECharts
      option={option}
      style={{ height: '100%', minHeight: 280 }}
      opts={{ renderer: 'canvas' }}
    />
  )
}
