// frontend-vue/src/components/charts/UsersChart.vue
<template>
  <div class="users-chart">
    <v-chart
      :option="chartOption"
      :autoresize="true"
      :style="{ height: height, width: '100%' }"
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { BarChart } from 'echarts/charts'
import {
  TitleComponent,
  TooltipComponent,
  GridComponent,
} from 'echarts/components'
import type { EChartsOption } from 'echarts'
import type { UserItem } from '@/types'

// 注册 ECharts 组件
use([
  CanvasRenderer,
  BarChart,
  TitleComponent,
  TooltipComponent,
  GridComponent,
])

interface Props {
  data?: UserItem[]
  height?: string
}

const props = withDefaults(defineProps<Props>(), {
  data: () => [],
  height: '400px',
})

const chartOption = computed<EChartsOption>(() => {
  // 按播放时长排序
  const sortedData = [...props.data].sort((a, b) => b.duration_hours - a.duration_hours)

  const usernames = sortedData.map((item) => item.username)
  const durations = sortedData.map((item) => item.duration_hours)

  return {
    tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'shadow',
      },
      formatter: (params: any) => {
        const data = params[0]
        return `${data.name}<br/>播放时长: ${data.value.toFixed(1)} 小时`
      },
    },
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true,
    },
    xAxis: {
      type: 'value',
      name: '播放时长 (小时)',
      nameTextStyle: {
        color: '#ccc',
      },
      axisLabel: {
        color: '#ccc',
      },
      axisLine: {
        lineStyle: {
          color: '#444',
        },
      },
      splitLine: {
        lineStyle: {
          color: '#333',
        },
      },
    },
    yAxis: {
      type: 'category',
      data: usernames,
      axisLabel: {
        color: '#ccc',
      },
      axisLine: {
        lineStyle: {
          color: '#444',
        },
      },
    },
    series: [
      {
        name: '播放时长',
        type: 'bar',
        data: durations,
        itemStyle: {
          color: {
            type: 'linear',
            x: 0,
            y: 0,
            x2: 1,
            y2: 0,
            colorStops: [
              { offset: 0, color: '#1976d2' },
              { offset: 1, color: '#42a5f5' },
            ],
          },
          borderRadius: [0, 4, 4, 0],
        },
        emphasis: {
          itemStyle: {
            color: {
              type: 'linear',
              x: 0,
              y: 0,
              x2: 1,
              y2: 0,
              colorStops: [
                { offset: 0, color: '#1565c0' },
                { offset: 1, color: '#1976d2' },
              ],
            },
          },
        },
      },
    ],
  }
})
</script>

<style scoped>
.users-chart {
  width: 100%;
}
</style>

// frontend/src/components/charts/UsersChart.tsx
import ReactECharts from 'echarts-for-react'
import type { UserItem } from '@/types'
import { useTheme } from '@/contexts/ThemeContext'

interface UsersChartProps {
  data: UserItem[]
}

export function UsersChart({ data }: UsersChartProps) {
  const { theme } = useTheme()
  const isDark = theme === 'dark'

  const colors = {
    tooltip: {
      bg: isDark ? '#18181b' : '#ffffff',
      border: isDark ? '#27272a' : '#e4e4e7',
      text: isDark ? '#ECEDEE' : '#18181b',
    },
    axis: {
      label: isDark ? '#71717a' : '#71717a',
      yLabel: isDark ? '#a1a1aa' : '#52525b',
      split: isDark ? '#27272a' : '#f4f4f5',
    },
  }

  const option = {
    backgroundColor: 'transparent',
    tooltip: {
      backgroundColor: colors.tooltip.bg,
      borderColor: colors.tooltip.border,
      textStyle: { color: colors.tooltip.text, fontSize: 12 },
    },
    grid: { left: '3%', right: '10%', top: '3%', bottom: '3%', containLabel: true },
    xAxis: {
      type: 'value',
      name: '小时',
      nameTextStyle: { color: colors.axis.label },
      axisLine: { show: false },
      axisLabel: { color: colors.axis.label, fontSize: 11 },
      splitLine: { lineStyle: { color: colors.axis.split } },
    },
    yAxis: {
      type: 'category',
      data: data.map((d) => d.username).reverse(),
      axisLine: { show: false },
      axisLabel: { color: colors.axis.yLabel, fontSize: 11 },
      axisTick: { show: false },
    },
    series: [
      {
        type: 'bar',
        data: data.map((d) => d.duration_hours).reverse(),
        itemStyle: {
          color: {
            type: 'linear',
            x: 0,
            y: 0,
            x2: 1,
            y2: 0,
            colorStops: [
              { offset: 0, color: '#006FEE' },
              { offset: 1, color: '#338ef7' },
            ],
          },
          borderRadius: [0, 4, 4, 0],
        },
        barWidth: '60%',
      },
    ],
  }

  return (
    <ReactECharts
      option={option}
      style={{ height: '100%', minHeight: 280 }}
      opts={{ renderer: 'canvas' }}
    />
  )
}
